version: '3.9'

services:
  web:
    image: nginx:1.23.1
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      # LETSENCRYPT_TEST: "true"
    volumes:
      - type: bind
        source: ./content
        target: /usr/share/nginx/html
        read_only: true
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
